import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/dev_main(4).png'
import AnimatedText from '@/components/AnimatedText'
import TypewriterText from "@/components/CartoonImage";
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import Hireme from '@/components/Hireme'
import TransitionEffect from "@/components/TransitionEffect";
import LightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
// import profilePic from '../../public/images/profile/developer-pic-1.png'



export default function Home() {
  return (
    <>
      <Head>
        
        <title>Niladri Ghoshal - WebDev-Portfolio</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light 2xl:'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>

      <div className='flex items-center justify-between w-full lg:flex-col '>

      <div className='w-1/2 md:w-full md:pb-8'>
        <Image src={profilePic} alt="Niladri Ghoshal" className='w-full h-auto lg:hidden md:inline-block md:w-full  '
        priority
        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
        />
      </div>
    <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center '>
      <AnimatedText  text="Using Code and Design to transform vision into reality." className='!text-5xl !text-left 
      xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl

      '/>
        <p className='my-4 text-base font-medium md:text-md sm:text-sm '>
        As a skilled full-stack developer, I am committed to transforming ideas into cutting-edge web applications. 
View my most recent works demonstrating my React.js and web development expertise.
        </p>

        <div className='flex items-center self-start mt-2 lg:self-center '>

    <Link href="/Niladri_Ghoshal_Resume.pdf" target='_blank' download={true} className='flex items-center bg-dark text-light px-6 p-2 rounded-lg text-lg font-semibold
    hover:bg-light hover:text-dark border-2 border-solid border-transparent
    hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
    md:p-2 md:px-4 md:text-base
    '>Resume
    
    <LinkArrow className={"w-6 ml-1"} />
    </Link>
    <Link href="mailto:niladrighoshal.20@gmail.com" target={'_blank'}
    className='ml-6 text-lg font-medium capitalize text-dark underline dark:text-light 
    md:text-base
    '
    >Contact</Link>


        </div>
      
    </div>

      </div>

        </Layout> 

        <Hireme />
        <div className='absolute right-8 bottom-58 inline-block w-24 '>
          {/* <Image src={LightBulb} alt='Light Bulb' className='w-full h-auto' /> */}
        </div>
        
        <div className='fixed right-4 bottom-4 flex items-center justify-between scale-0.5 overflow-hidden md:hidden '> 
        <TypewriterText />
        </div>
        
      </main>

    </>
  )
}
